// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXftITSh07Hcus5H7tYp-IOKN8HZ_szwE',
    appId: '1:1082269849127:web:0aef0b284bb6ae4638e002',
    messagingSenderId: '1082269849127',
    projectId: 'bem-estar-13a2d',
    authDomain: 'bem-estar-13a2d.firebaseapp.com',
    storageBucket: 'bem-estar-13a2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0nDrkj4TNEK5ZBxwYj74kkZVfbvZiSf4',
    appId: '1:1082269849127:android:1832fcc340d783ac38e002',
    messagingSenderId: '1082269849127',
    projectId: 'bem-estar-13a2d',
    storageBucket: 'bem-estar-13a2d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf6wFQXnuH25XWvnnLvgyNtiNI5dBGtvM',
    appId: '1:1082269849127:ios:1e85c7972e836cb138e002',
    messagingSenderId: '1082269849127',
    projectId: 'bem-estar-13a2d',
    storageBucket: 'bem-estar-13a2d.firebasestorage.app',
    iosBundleId: 'com.example.bemEstar',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf6wFQXnuH25XWvnnLvgyNtiNI5dBGtvM',
    appId: '1:1082269849127:ios:1e85c7972e836cb138e002',
    messagingSenderId: '1082269849127',
    projectId: 'bem-estar-13a2d',
    storageBucket: 'bem-estar-13a2d.firebasestorage.app',
    iosBundleId: 'com.example.bemEstar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXftITSh07Hcus5H7tYp-IOKN8HZ_szwE',
    appId: '1:1082269849127:web:8dfb6faea7f9479c38e002',
    messagingSenderId: '1082269849127',
    projectId: 'bem-estar-13a2d',
    authDomain: 'bem-estar-13a2d.firebaseapp.com',
    storageBucket: 'bem-estar-13a2d.firebasestorage.app',
  );
}
